runtime: python38
instance_class: F1
env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: onelib
  MYSQL_DB: onelib
  MYSQL_HOST: "34.134.18.205"

handlers:
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles